### ISSUE TITLE
将MidiProduce的主要逻辑复制到mider，以实现脱离MiraiPlugin复用

### ISSUE THREAD

**Issue by hundun000** [whiterasbk/mider#1]
MidiProduce主要逻辑指的是：(String) -> InputStream，即输入音符序列文本，输出音频数据流。

可以看成提供一种编写kotlin类以外的使用mider的方法——使用音符序列文本作为输入。《简单使用》也将更加简单：即使不懂乐理知识 ~~(比如我)~~，也可以尝试替换不同的音符序列，得到不同输出。

如果你觉得合适，我可以尝试提供PR。

**Comment by whiterasbk** [comment]
我觉得可以, 不过现在有两个~小~问题: 
 1. `MiderDSL` 内有一个解析字符串格式类似 `C[pith,duration] D[pith,duration]` (标准音名序列) 的 `parse` 方法, 为避免重复, 新建解析 `MidiProduce` 中 **音名** 序列 的方法 **建议** 取名为 `parseScrawlNote` ~直白的翻译就是解析鬼画符(~
 2. `mider-dsl` 因为没空写文档所以比较难以扩展, ~所以请自备降压药~

BTW: 
 1. `MiderDSL` 中添加音符的方法是`push('NoteName')`, 修改当前音符音高的方法是 `current + pitch` 修改当前音符时值的方法是 `current * duration`, 其本质是对 `list` 中的元素进行操作
 2. ~当前版本 `MidiProduce` 中关于音名序列的解析不能做到区分**前缀修改字符**和**后缀修改字符**, 都当成后缀修改字符处理了; 我在将来的版本中有计划修改这部分逻辑使之支持区分前后缀修改字符(已经实现了 2022.5.28~
 3.  `NoteListParser.kt` 和 `MiderDSL.kt` 实现的方式和定义的数据结构过于粗暴, 有计划进行大改(~越写越想重构~

关于**前缀/后缀修改**字符 (见`toMiderNoteList`方法下的`noteModifyChars`变量): 
以音名为基础, **只应该**出现在音名前的是前缀修改字符, 如 `#F` 中的`#`号, 同理后缀修改字符是**只应该**出现在音名后面的字符, 如 `F6` 中的数字 `6`
现在启用的修改字符 
前缀修改字符: `$` `#` `&` `:`
 后缀修改字符: `0-9` `+` `-` `.`

**Comment by hundun000** [comment]
之前没看仔细，我才看到midiNote是在mider的。我还以为是为了适应从指令输入专门写在MidiProduce里，mider只是用DSL以单个音为单位编写的。原来mider也能parseMidiNote，那好像也没必要新增parseScrawlNote了。

**Comment by hundun000** [comment]
不过DSL里的`String.not()`确实容易误导吧？我一开始看MidiProduce完全没注意到`!`会是mider里的parseMidiNote

**Comment by whiterasbk** [comment]
`mider`能单独解析String有两种格式，一种是标准的，只含`A~G`和`O`的音名序列，格式只能是`A[pitch,duration] B[pitch,duration]....C[pitch,duration]`, 表现力不如`MidiProduce`的格式
另一种是包含`0~9`和`.`的数字格式, 可以用于解析简谱, 但表现力同样不如`MidiProduce`提供的格式

我以为你说的是要把这两种格式的解析换成`MidiProduce`那种表现力更强的解析实现

`String.not`运算符确实容易误导, 下个版本可能会换成`unaryPlus`

**Comment by hundun000** [comment]
好，那还是可以尝试将MidiProduce提供的格式移进来。不如顺便将格式的命名定下来，也别叫ScrawlNote，不如就叫miderCode？（叫“code”因为他不仅可以是“note”，包括不限于bpm也可设定。类似mirai约定了名为miraiCode的格式）

StandardNote: A[pitch,duration]
NumberedNote:  包含0~9和.
MiderCode: 对于音符part，支持Standard和Numbered；还包括bpm part等

**Comment by whiterasbk** [comment]
`MiderCode` 的命名可以
但 `StanderNote` 和 `MiderCode` 是不一样的
前者的目的是做到最大程度和 `mider-dsl` 语法 一致, 也为了方便机器顺序解析
后者更倾向于通过各种宏和前后缀修改字符达到简洁~直观~的效果
而目前的做法是将 `MiderCode` 解析为 `StanderCode` 再解析为 `List<Note>` 最后解析为 `midi`
所以 , 目前 `StanderCode` 更类似一种中间语言的存在

>NumberedNote: 包含0~9和.

建议改为 `NumberedNotation`, Notation 表示记谱法
 
`NumberedNote` 或 `NumberedNotation` 是 `MiderCode` 的变体, 在 `MidiProduce` 中两个实现方式是杂糅在一起的
两者的区别仅是 音名换成唱名, 唱名换成音名和个别规则的不同

PS: 
`MiderDsl` 中确实有个 `parseInt` 方法, 但是那个方法的设计目标是做到使用十个阿拉伯数字就能映射现行 `midi` 规范中的 128 个音
~啊这有什么用?确实没什么卵用, 只是之前好奇想解析pi(~

**Comment by hundun000** [comment]
那我就不动原有命名了。只要搬进来时命名MiderCode没问题就行。

**Comment by whiterasbk** [comment]
好 OωO

**Comment by hundun000** [comment]
缺少Config和MacroConfiguration，MidiProduce也没法复用啊。你看看 #3 这样从外部接受呢？

**Comment by whiterasbk** [comment]
@hundun000  草, 太急了忘了, MiderCodeParseCondition  有什么用?

**Comment by hundun000** [comment]
> @hundun000 草, 太急了忘了, MiderCodeParseCondition 有什么用?

代替Config，且仅取Config中和调控Parse有关的部分，目前仅有`var isBlankReplaceWith0`，未来可以更多

**Comment by whiterasbk** [comment]
> 缺少Config和MacroConfiguration，MidiProduce也没法复用啊。你看看 #3 这样从外部接受呢？

Config 里关于 MiderCode的配置 只有 recursionLimit 
```kotlin
    @ValueDescription("include 最大深度")
    val recursionLimit by value(50)
```

而 recursionLimit 是 MacroConfiguration 自带的属性, 给出 MacroConfiguration 那么 recursionLimit 就是确定的了

**Comment by whiterasbk** [comment]
> > @hundun000 草, 太急了忘了, MiderCodeParseCondition 有什么用?
> 
> 代替Config，且仅取Config中和调控Parse有关的部分，目前仅有`var isBlankReplaceWith0`，未来可以更多

不如这样, 把 MacroConfiguration 的功能合并到 MiderCodeParseCondition 里并更名为MiderCodeParserConfiguration, MacroConfiguration不给也有默认实现, 这样传递一个参数就足够了 @hundun000

**Comment by hundun000** [comment]
嗯，能让MidiProduce正常使用就行。确认能正常使用issue就可以关了

**Comment by whiterasbk** [comment]
好
